---
- name: CREATE LOOPBACK INTERFACE WITH IPv4 AND IPv6 ADDRESSES
  hosts: iosxe_reserved
  gather_facts: False
  connection: local
  become: yes
  become_method: enable

  tasks:
    - name: Creating Loopback interface
      ios_interface:
        name: Loopback10
        enabled: True
        description: "Loopback interface created with Ansible"

    - name: Assign IPv4 to Loopback interface
      ios_l3_interface:
        name: Loopback10
        ipv4: 192.168.2.1/32

    - name: Assign first IPv6 address to Loopback interface
      ios_l3_interface:
        name: Loopback10
        ipv6: 2001:db8::1/128

    - name: Assign second IPv6 address to Loopback interface
      ios_l3_interface:
        name: Loopback10
        ipv6: 2001:db8::2/128
