---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: iosxe_reserved
  gather_facts: false
  connection: local
 
  tasks:
   - name: DISPLAYING THE RUNNING-CONFIG
     ios_command:
       commands:
         - show running-config  
     register: config
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "/home/devasc/Documents/IaCExperiments/AnsibleVirtualRouter/script_voor_loopback_ipv4_ipv6_show_run.txt"
