---
- name: DISCOVER IOS VERSION 
  hosts: iosxe_reserved
  gather_facts: False
  connection: local
 
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version
    register: result_show_version

  - name: Display output of show version command
    debug:
      var: result_show_version.stdout

  - name: run show version and check to see if output contains IOS
    ios_command:
      commands: show version
    register: result_show_version_check

  - name: Display output of show version check
    debug:
      var: result_show_version_check.stdout

  - name: run multiple commands on remote nodes
    ios_command:
      commands:
        - show version
        - show interfaces
    register: result_multiple_commands

  - name: Display output of multiple commands
    debug:
      var: result_multiple_commands.stdout

  - name: run multiple commands and evaluate the output
    ios_command:
      commands:
        - show version
        - show interfaces
    register: result_evaluate_multiple_commands

  - name: Display output of evaluated multiple commands
    debug:
      var: result_evaluate_multiple_commands.stdout
