---
- name: CONFIGURE DEVICE HOSTNAME
  hosts: iosxr_reserved
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
  - name: update hostname
    ios_system:
      hostname: "xrv9k_StefanYS"
